services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - api-gateway

  api-gateway:
    build: ./backend/api-gateway
    ports:
      - "8001:8000"
    depends_on:
      - content-service
      - rec-service
      - event-service

  content-service:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/lockscreen
      - NEWS_API_KEY=${NEWS_API_KEY}
      - UNSPLASH_KEY=${UNSPLASH_KEY}
    depends_on:
      - db

  rec-service:
    build: ./backend/rec-service
    ports:
      - "8002:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/lockscreen
    depends_on:
      - db

  event-service:
    build: ./backend/event-service
    ports:
      - "8003:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/lockscreen
    depends_on:
      - db

  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: lockscreen
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
